chore: add contributor spotlight markdown file
mdn/mdn pull request #264
Opened 2022-12-04 19:25 UTC by schalkneethling

Adds spotlight contributor markdown file and a pull request template to use when nominating someone for a particular role.

fix #263

2022-12-05 09:04 UTC, bsmth commented
Taking a look 👀

2022-12-05 09:11 UTC, bsmth commented on spotlight-contributors/index.md
> +- [On MDN Web Docs](https://developer.mozilla.org/en-US/community/spotlight/mikoMK)
```suggestion
- [On MDN Web Docs](https://developer.mozilla.org/en-US/community/spotlight/michael-koch)
```

2022-12-05 09:13 UTC, bsmth approved these changes
Looks good to me 👍🏻

2022-12-05 18:52 UTC, dipikabh requested changes
This looks great, @schalkneethling! Thank you. I have added a few suggestions and comments.

2022-12-05 18:52 UTC, dipikabh commented on .github/PULL_REQUEST_TEMPLATE/pull-request-template.md
> +# Nominating [GitHub username] as a [role]
Should we name this file `index.md`? Also we can follow lower case for the folder name. How about naming the folder something along these lines:
`.github/nomination_pull_request_template/index.md`

2022-12-05 18:52 UTC, dipikabh commented on .github/PULL_REQUEST_TEMPLATE/pull-request-template.md
> +Thank you for taking the time to nominate a fellow contributor. Make sure you read our [list of prerequisites](https://developer.mozilla.org/en-US/docs/MDN/Community/Users_teams) for the relevant rol
```suggestion
Thank you for taking the time to nominate a fellow contributor. Make sure you read our [list of prerequisites](https://developer.mozilla.org/en-US/docs/MDN/Community/Users_teams) for the relevant role before submitting a nomination.
Please submit information for the person you are nominating in the sections listed below.
```

2022-12-05 18:52 UTC, dipikabh commented on .github/PULL_REQUEST_TEMPLATE/pull-request-template.md
> +## Why are you nominating this person? (required)
```suggestion
## Reason for nominating this person (required)
```

2022-12-05 18:52 UTC, dipikabh commented on .github/PULL_REQUEST_TEMPLATE/pull-request-template.md
> +## GitHub username (required)
```suggestion
## GitHub username of the nominee (required)
```

2022-12-05 18:52 UTC, dipikabh commented on .github/PULL_REQUEST_TEMPLATE/pull-request-template.md
> +## GitHub profile link (required)
```suggestion
## GitHub profile link of the nominee (required)
```

2022-12-05 18:52 UTC, dipikabh commented on .github/PULL_REQUEST_TEMPLATE/pull-request-template.md
> +## Supporting evidence (required)
```suggestion
## Supporting evidence for nominating this person (required)
```

2022-12-05 18:52 UTC, dipikabh commented on .github/PULL_REQUEST_TEMPLATE/pull-request-template.md
> +Links to [commit logs](https://github.com/mdn/yari/commits?author=schalkneethling) in a repository are also appropriate.
```suggestion
Provide evidence to support your nomination. The supporting information can include a list of their contributions and interactions with the community.
You can also provide links to [commit logs](https://github.com/mdn/yari/commits?author=schalkneethling).
```

2022-12-05 18:52 UTC, dipikabh commented on spotlight-contributors/index.md
> +# MDN Web Docs Spotlight Contributors
```suggestion
# MDN Web Docs spotlight contributors
```

Also, how about the folder name `spolight_contributors`?

2022-12-05 18:52 UTC, dipikabh commented on spotlight-contributors/index.md
> +## Spotlight Contributors
```suggestion
## Archive of our spotlight contributors
```

2022-12-05 18:52 UTC, dipikabh commented on spotlight-contributors/index.md
> +### Carolyn Wu
Would it make sense to capture the month and year when the spotlight was on them?

```suggestion
### Carolyn Wu
August, 2022
```

2022-12-05 19:05 UTC, schalkneethling commented on .github/PULL_REQUEST_TEMPLATE/pull-request-template.md
> +# Nominating [GitHub username] as a [role]
From what I can tell from the GitHub docs, pull request templates are still very primitive :) and so, you can only have one, really. They have some guidance as to naming, and this is one of the ways. It is also how we do it on other repos. On Yari with have it at the root: https://github.com/mdn/yari/tree/main/.github

2022-12-05 19:07 UTC, schalkneethling commented on spotlight-contributors/index.md
> +### Carolyn Wu
Yeah, good idea. I was. thinking of doing that. I hope I can get the appropriate month from the GitHub repo :)

2022-12-05 19:35 UTC, dipikabh approved these changes
Thanks for the fixes, @schalkneethling!

2022-12-05 19:35 UTC, dipikabh commented
For the two folder names, I guess I was following the conventions we've described in [Documentation conventions](https://github.com/mdn/content/blob/main/CONTRIBUTING.md#documentation-conventions). So we name the markdown file inside a folder as `index.md`, and we use lower case and underscores in the folder names.

2022-12-05 23:10 UTC, schalkneethling commented
> For the two folder names, I guess I was following the conventions we've described in [Documentation conventions](https://github.com/mdn/content/blob/main/CONTRIBUTING.md?rgh-link-date=2022-12-05T19%3A35%3A31Z#documentation-conventions). So we name the markdown file inside a folder as `index.md`, and we use lower case and underscores in the folder names.

100% - I think here we diverge as this is more a GitHub thing. Thank you for the review, @dipikabh

2022-12-05 23:29 UTC, merged

2024-01-05 19:56 UTC, Elenore23 commented
> Adds spotlight contributor markdown file and a pull request template to use when nominating someone for a particular role.
> 
> fix #263
>